version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - local_pgdata_nosql:/var/lib/postgresql/data
volumes:
  local_pgdata_nosql:
